$FirebaseSDKVersion = '10.3.0'

# Resolve react_native_pods.rb with node to allow for hoisting
def node_require(script)
  # Resolve script with node to allow for hoisting
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
      '#{script}',
      {paths: [process.argv[1]]},
    )", __dir__]).strip
end

 node_require('react-native/scripts/react_native_pods.rb')
 node_require('react-native-permissions/scripts/setup.rb')

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'GLOCONLive' do
  use_frameworks! :linkage => :static
  $RNFirebaseAsStaticFramework = true
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # RNPermissions fix: force static libs
  pre_install do |installer|
    Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}

    installer.pod_targets.each do |pod|
      if pod.name.eql?('RNPermissions') || pod.name.start_with?('Permission-')
        def pod.build_type;
          Pod::BuildType.static_library
        end
      end
    end
  end
  setup_permissions(['Camera', 'Microphone'])
end

post_install do |installer|
  react_native_post_install(
    installer,
    :mac_catalyst_enabled => false,
     # :ccache_enabled => true
  )
  
  # Fix for Xcode 15 build issues (new clang + glog/folly)
  # installer.pods_project.targets.each do |target|
  #   target.build_configurations.each do |config|
  #     config.build_settings["BUILD_LIBRARY_FOR_DISTRIBUTION"] = "YES"
  #   end
  # end

  installer.pods_project.targets.each do |target|
  # Allow non-modular includes for RNFirebase pods to fix
  # "include of non-modular header inside framework module" errors
  if ['RNFBApp', 'RNFBAnalytics', 'RNFBCrashlytics', 'RNFBRemoteConfig', 'RNFBAppCheck'].include?(target.name)
    target.build_configurations.each do |config|
      config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
      config.build_settings['DEFINES_MODULE'] = 'NO'
    end
  end
end
end