export const actionTypes = {
  IS_LOADING: 'IS_LOADING',
  SET_AUTH: 'SET_AUTH',
  UPDATE_AUTH: 'UPDATE_AUTH',
};

export const profileActionTypes = {
  STORE_PROFILE: 'STORE_PROFILE',
};

export const shopVideoActionTypes = {
  SET_SHOP_VIDEO: 'SET_SHOP_VIDEO',
};

export const locationActionTypes = {
  STORE_LOCATION: 'STORE_LOCATION',
  APPEND_LOCATION: 'APPEND_LOCATION',
  UPDATE_LOCATION: 'UPDATE_LOCATION',
};

export const departmentActionTypes = {
  STORE_DEPARTMENT: 'STORE_DEPARTMENT',
  APPEND_DEPARTMENT: 'APPEND_DEPARTMENT',
  UPDATE_DEPARTMENT: 'UPDATE_DEPARTMENT',
};

export const chatActionTypes = {
  INIT_ZIM_INSTANCE: 'INIT_ZIM_INSTANCE',
  CLEAR_CHAT: 'CLEAR_CHAT',
  SET_CHAT: 'SET_CHAT',
  SET_ZIM_LOGIN: 'SET_ZIM_LOGIN',
  SET_ZIM_USER_MAP: 'SET_ZIM_USER_MAP',
  SET_ZIM_USER: 'SET_ZIM_USER'
}
